name: adoptame
description: Una aplicaciÃ³n para adoptar mascotas.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #cloud_firestore: ^0.12.1
  flutter_launcher_icons: ^0.7.0
  splashscreen: ^1.2.0
  cloud_firestore: ^0.9.5+2
  firebase_storage: ^2.1.0+1
  image_picker: ^0.5.0+3
  cached_network_image: ^0.7.0
  meta: ^1.1.6
  firebase_core: ^0.3.1+1
  firebase_auth: ^0.8.1+4
  flutter_auth_buttons: ^0.3.1
  url_launcher: ^5.0.2
  firebase_messaging: ^4.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_sign_in: ^4.0.1+1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/x2/pp.jpg
    - assets/splash.png
    - assets/pet.png
    - assets/login.png
    - assets/icon.png
    - assets/googlesignin.png
    - assets/gato.jpg
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico.ttf